"""sync models with missing columns and tables

Revision ID: ca45f68ec9a7
Revises: b9f4e2c8d310
Create Date: 2026-06-17 14:59:17.963193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca45f68ec9a7'
down_revision: Union[str, Sequence[str], None] = 'b9f4e2c8d310'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('receipts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=True),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('ocr_text', sa.Text(), nullable=True),
    sa.Column('vendor', sa.String(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('receipt_date', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_receipts_id'), 'receipts', ['id'], unique=False)
    op.create_index('ix_receipts_tenant_id', 'receipts', ['tenant_id'], unique=False)
    op.create_table('audit_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_entries_id'), 'audit_entries', ['id'], unique=False)
    op.create_index('ix_audit_entries_tenant_id', 'audit_entries', ['tenant_id'], unique=False)
    op.create_table('batch_import_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('total_rows', sa.Integer(), nullable=True),
    sa.Column('processed_rows', sa.Integer(), nullable=True),
    sa.Column('error_rows', sa.Integer(), nullable=True),
    sa.Column('error_log', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_batch_import_jobs_id'), 'batch_import_jobs', ['id'], unique=False)
    op.create_index('ix_batch_import_jobs_tenant_id', 'batch_import_jobs', ['tenant_id'], unique=False)
    op.create_table('budgets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('period_start', sa.String(), nullable=False),
    sa.Column('period_end', sa.String(), nullable=False),
    sa.Column('total_budget', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_budgets_id'), 'budgets', ['id'], unique=False)
    op.create_index('ix_budgets_tenant_id', 'budgets', ['tenant_id'], unique=False)
    op.create_table('exchange_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('from_currency', sa.String(), nullable=False),
    sa.Column('to_currency', sa.String(), nullable=False),
    sa.Column('rate', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('rate_date', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exchange_rates_id'), 'exchange_rates', ['id'], unique=False)
    op.create_index('ix_exchange_rates_tenant_id', 'exchange_rates', ['tenant_id'], unique=False)
    op.create_table('firm_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('firm_name', sa.String(), nullable=True),
    sa.Column('firm_address', sa.Text(), nullable=True),
    sa.Column('firm_phone', sa.String(), nullable=True),
    sa.Column('firm_email', sa.String(), nullable=True),
    sa.Column('firm_ein', sa.String(), nullable=True),
    sa.Column('logo_path', sa.String(), nullable=True),
    sa.Column('fiscal_year_end', sa.String(), nullable=True),
    sa.Column('timezone', sa.String(), nullable=True),
    sa.Column('date_format', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_firm_settings_id'), 'firm_settings', ['id'], unique=False)
    op.create_index('ix_firm_settings_tenant_id', 'firm_settings', ['tenant_id'], unique=False)
    op.create_table('journal_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('entry_number', sa.String(), nullable=False),
    sa.Column('entry_date', sa.String(), nullable=False),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('is_reversed', sa.Boolean(), nullable=True),
    sa.Column('reversed_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['reversed_by_id'], ['journal_entries.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_journal_entries_id'), 'journal_entries', ['id'], unique=False)
    op.create_index('ix_journal_entries_tenant_id', 'journal_entries', ['tenant_id'], unique=False)
    op.create_table('periods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('start_date', sa.String(), nullable=False),
    sa.Column('end_date', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('is_locked', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_periods_id'), 'periods', ['id'], unique=False)
    op.create_index('ix_periods_tenant_id', 'periods', ['tenant_id'], unique=False)
    op.create_table('recurring_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tx_type', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('frequency', sa.String(), nullable=False),
    sa.Column('day_of_month', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.String(), nullable=True),
    sa.Column('end_date', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_generated', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recurring_templates_id'), 'recurring_templates', ['id'], unique=False)
    op.create_index('ix_recurring_templates_tenant_id', 'recurring_templates', ['tenant_id'], unique=False)
    op.create_table('signed_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('report_type', sa.String(), nullable=False),
    sa.Column('period_start', sa.String(), nullable=True),
    sa.Column('period_end', sa.String(), nullable=True),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('signed_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('signature_hash', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_signed_reports_id'), 'signed_reports', ['id'], unique=False)
    op.create_index('ix_signed_reports_tenant_id', 'signed_reports', ['tenant_id'], unique=False)
    op.create_table('transaction_flags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('flag_type', sa.String(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transaction_flags_id'), 'transaction_flags', ['id'], unique=False)
    op.create_index('ix_transaction_flags_tenant_id', 'transaction_flags', ['tenant_id'], unique=False)
    op.create_table('transaction_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transaction_notes_id'), 'transaction_notes', ['id'], unique=False)
    op.create_index('ix_transaction_notes_tenant_id', 'transaction_notes', ['tenant_id'], unique=False)
    op.create_table('bank_connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('institution_name', sa.String(), nullable=False),
    sa.Column('connection_type', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('last_sync', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bank_connections_id'), 'bank_connections', ['id'], unique=False)
    op.create_index('ix_bank_connections_tenant_id', 'bank_connections', ['tenant_id'], unique=False)
    op.create_table('budget_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('budget_id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['budget_id'], ['budgets.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_budget_entries_id'), 'budget_entries', ['id'], unique=False)
    op.create_index('ix_budget_entries_tenant_id', 'budget_entries', ['tenant_id'], unique=False)
    op.create_table('journal_entry_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('journal_entry_id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('account_code', sa.String(), nullable=False),
    sa.Column('account_name', sa.String(), nullable=True),
    sa.Column('debit', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('credit', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['journal_entry_id'], ['journal_entries.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_journal_entry_lines_id'), 'journal_entry_lines', ['id'], unique=False)
    op.create_index('ix_journal_entry_lines_tenant_id', 'journal_entry_lines', ['tenant_id'], unique=False)
    op.add_column('transactions', sa.Column('client_id', sa.Integer(), nullable=True))
    op.add_column('transactions', sa.Column('journal_entry_id', sa.Integer(), nullable=True))
    op.add_column('transactions', sa.Column('receipt_id', sa.Integer(), nullable=True))
    op.add_column('transactions', sa.Column('confirmed', sa.Boolean(), nullable=True))
    op.add_column('transactions', sa.Column('is_manual', sa.Boolean(), nullable=True))
    op.add_column('transactions', sa.Column('is_journal', sa.Boolean(), nullable=True))
    op.add_column('transactions', sa.Column('archived', sa.Boolean(), nullable=True))
    op.add_column('transactions', sa.Column('source_pdf_path', sa.String(), nullable=True))
    op.add_column('transactions', sa.Column('tax_line', sa.String(), nullable=True))
    op.add_column('transactions', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
    op.create_index('ix_transactions_category', 'transactions', ['category'], unique=False)
    op.create_index('ix_transactions_date', 'transactions', ['date'], unique=False)
    # SQLite does not support ALTER TABLE ADD FOREIGN KEY; skip FK additions there.
    # Foreign key relationships are still defined in the SQLAlchemy models.
    conn = op.get_bind()
    if conn.dialect.name == "postgresql":
        op.create_foreign_key(None, 'transactions', 'receipts', ['receipt_id'], ['id'])
        op.create_foreign_key(None, 'transactions', 'clients', ['client_id'], ['id'])
        op.create_foreign_key(None, 'transactions', 'journal_entries', ['journal_entry_id'], ['id'])
    op.add_column('users', sa.Column('role', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    conn = op.get_bind()
    if conn.dialect.name == "postgresql":
        op.drop_constraint(None, 'transactions', type_='foreignkey')
        op.drop_constraint(None, 'transactions', type_='foreignkey')
        op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_index('ix_transactions_date', table_name='transactions')
    op.drop_index('ix_transactions_category', table_name='transactions')
    op.drop_column('transactions', 'updated_at')
    op.drop_column('transactions', 'tax_line')
    op.drop_column('transactions', 'source_pdf_path')
    op.drop_column('transactions', 'archived')
    op.drop_column('transactions', 'is_journal')
    op.drop_column('transactions', 'is_manual')
    op.drop_column('transactions', 'confirmed')
    op.drop_column('transactions', 'receipt_id')
    op.drop_column('transactions', 'journal_entry_id')
    op.drop_column('transactions', 'client_id')
    op.drop_index('ix_journal_entry_lines_tenant_id', table_name='journal_entry_lines')
    op.drop_index(op.f('ix_journal_entry_lines_id'), table_name='journal_entry_lines')
    op.drop_table('journal_entry_lines')
    op.drop_index('ix_budget_entries_tenant_id', table_name='budget_entries')
    op.drop_index(op.f('ix_budget_entries_id'), table_name='budget_entries')
    op.drop_table('budget_entries')
    op.drop_index('ix_bank_connections_tenant_id', table_name='bank_connections')
    op.drop_index(op.f('ix_bank_connections_id'), table_name='bank_connections')
    op.drop_table('bank_connections')
    op.drop_index('ix_transaction_notes_tenant_id', table_name='transaction_notes')
    op.drop_index(op.f('ix_transaction_notes_id'), table_name='transaction_notes')
    op.drop_table('transaction_notes')
    op.drop_index('ix_transaction_flags_tenant_id', table_name='transaction_flags')
    op.drop_index(op.f('ix_transaction_flags_id'), table_name='transaction_flags')
    op.drop_table('transaction_flags')
    op.drop_index('ix_signed_reports_tenant_id', table_name='signed_reports')
    op.drop_index(op.f('ix_signed_reports_id'), table_name='signed_reports')
    op.drop_table('signed_reports')
    op.drop_index('ix_recurring_templates_tenant_id', table_name='recurring_templates')
    op.drop_index(op.f('ix_recurring_templates_id'), table_name='recurring_templates')
    op.drop_table('recurring_templates')
    op.drop_index('ix_periods_tenant_id', table_name='periods')
    op.drop_index(op.f('ix_periods_id'), table_name='periods')
    op.drop_table('periods')
    op.drop_index('ix_journal_entries_tenant_id', table_name='journal_entries')
    op.drop_index(op.f('ix_journal_entries_id'), table_name='journal_entries')
    op.drop_table('journal_entries')
    op.drop_index('ix_firm_settings_tenant_id', table_name='firm_settings')
    op.drop_index(op.f('ix_firm_settings_id'), table_name='firm_settings')
    op.drop_table('firm_settings')
    op.drop_index('ix_exchange_rates_tenant_id', table_name='exchange_rates')
    op.drop_index(op.f('ix_exchange_rates_id'), table_name='exchange_rates')
    op.drop_table('exchange_rates')
    op.drop_index('ix_budgets_tenant_id', table_name='budgets')
    op.drop_index(op.f('ix_budgets_id'), table_name='budgets')
    op.drop_table('budgets')
    op.drop_index('ix_batch_import_jobs_tenant_id', table_name='batch_import_jobs')
    op.drop_index(op.f('ix_batch_import_jobs_id'), table_name='batch_import_jobs')
    op.drop_table('batch_import_jobs')
    op.drop_index('ix_audit_entries_tenant_id', table_name='audit_entries')
    op.drop_index(op.f('ix_audit_entries_id'), table_name='audit_entries')
    op.drop_table('audit_entries')
    op.drop_index('ix_receipts_tenant_id', table_name='receipts')
    op.drop_index(op.f('ix_receipts_id'), table_name='receipts')
    op.drop_table('receipts')
    # ### end Alembic commands ###
