"""add_transaction_flag_resolution_and_firm_settings_confidence

Revision ID: d624428edb28
Revises: ca45f68ec9a7
Create Date: 2026-06-17 16:58:00.543388

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd624428edb28'
down_revision: Union[str, Sequence[str], None] = 'ca45f68ec9a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('firm_settings', sa.Column('recurring_high_confidence', sa.Numeric(precision=5, scale=4), nullable=True))
    op.add_column('firm_settings', sa.Column('recurring_medium_confidence', sa.Numeric(precision=5, scale=4), nullable=True))
    op.add_column('firm_settings', sa.Column('recurring_auto_confirm', sa.Numeric(precision=5, scale=4), nullable=True))
    op.add_column('firm_settings', sa.Column('receipt_match_amount_weight', sa.Numeric(precision=3, scale=2), nullable=True))
    op.add_column('firm_settings', sa.Column('receipt_match_date_weight', sa.Numeric(precision=3, scale=2), nullable=True))
    op.add_column('firm_settings', sa.Column('receipt_match_description_weight', sa.Numeric(precision=3, scale=2), nullable=True))
    op.add_column('transaction_flags', sa.Column('is_resolved', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('transaction_flags', sa.Column('resolved_by', sa.Integer(), nullable=True))
    op.add_column('transaction_flags', sa.Column('resolved_at', sa.DateTime(), nullable=True))
    # SQLite does not support ALTER TABLE ADD FOREIGN KEY; skip FK additions there.
    conn = op.get_bind()
    if conn.dialect.name == "postgresql":
        op.create_foreign_key(None, 'transaction_flags', 'users', ['resolved_by'], ['id'])
        op.create_foreign_key(None, 'transactions', 'journal_entries', ['journal_entry_id'], ['id'])
        op.create_foreign_key(None, 'transactions', 'clients', ['client_id'], ['id'])
        op.create_foreign_key(None, 'transactions', 'receipts', ['receipt_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    if conn.dialect.name == "postgresql":
        op.drop_constraint(None, 'transactions', type_='foreignkey')
        op.drop_constraint(None, 'transactions', type_='foreignkey')
        op.drop_constraint(None, 'transactions', type_='foreignkey')
        op.drop_constraint(None, 'transaction_flags', type_='foreignkey')
    op.drop_column('transaction_flags', 'resolved_at')
    op.drop_column('transaction_flags', 'resolved_by')
    op.drop_column('transaction_flags', 'is_resolved')
    op.drop_column('firm_settings', 'receipt_match_description_weight')
    op.drop_column('firm_settings', 'receipt_match_date_weight')
    op.drop_column('firm_settings', 'receipt_match_amount_weight')
    op.drop_column('firm_settings', 'recurring_auto_confirm')
    op.drop_column('firm_settings', 'recurring_medium_confidence')
    op.drop_column('firm_settings', 'recurring_high_confidence')
    # ### end Alembic commands ###
