"""Add trained_models table

Revision ID: d9cf7c4a8fdf
Revises: 35b27f93b50d
Create Date: 2026-06-23 10:09:02.711310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9cf7c4a8fdf'
down_revision: Union[str, Sequence[str], None] = '35b27f93b50d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trained_models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('model_path', sa.String(), nullable=False),
    sa.Column('model_sha256', sa.String(length=64), nullable=False),
    sa.Column('accuracy', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('f1_macro', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('support', sa.Integer(), nullable=True),
    sa.Column('classes', sa.String(), nullable=True),
    sa.Column('trained_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trained_models_id'), 'trained_models', ['id'], unique=False)
    op.create_index('ix_trained_models_is_active', 'trained_models', ['is_active'], unique=False)
    op.create_index('ix_trained_models_tenant_id', 'trained_models', ['tenant_id'], unique=False)
    op.create_index('ix_trained_models_user_id', 'trained_models', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_trained_models_user_id', table_name='trained_models')
    op.drop_index('ix_trained_models_tenant_id', table_name='trained_models')
    op.drop_index('ix_trained_models_is_active', table_name='trained_models')
    op.drop_index(op.f('ix_trained_models_id'), table_name='trained_models')
    op.drop_table('trained_models')
    # ### end Alembic commands ###
