"""Temporary file cleanup utilities for TaxFlow Pro v3.9.2 (TASK-035).

Guarantees that uploaded PDFs, OCR conversion images, and any orphaned
export/scratch files are removed after use or after a configurable age.
"""
from __future__ import annotations

import asyncio
import logging
import os
import shutil
import tempfile
import time
from pathlib import Path
from typing import Iterable, List

from backend.api_utils import get_upload_dir

logger = logging.getLogger("taxflow.temp_cleanup")

# Filenames/prefixes generated by pdf2image or TaxFlow OCR paths.
_OCR_PREFIXES = ("pdf2image", "tmp", "ocr_", "ppm-", "png-")
_OCR_SUFFIXES = (".png", ".ppm", ".pbm", ".pgm", ".jpg", ".jpeg")


def _is_ocr_temp_file(path: Path) -> bool:
    """Return True if the file looks like a pdf2image/OCR scratch file."""
    name_lower = path.name.lower()
    return (
        name_lower.startswith(_OCR_PREFIXES)
        or name_lower.endswith(_OCR_SUFFIXES)
        or "pdf2image" in name_lower
    )


def cleanup_uploaded_file(path: Path | str) -> bool:
    """Delete a single uploaded PDF/scratch file, logging the outcome.

    Returns True if the file no longer exists after the call.
    """
    target = Path(path)
    try:
        if target.exists():
            target.unlink()
            logger.info("Deleted uploaded scratch file: %s", target)
        return True
    except Exception as exc:  # pragma: no cover - best-effort cleanup
        logger.warning("Failed to delete uploaded scratch file %s: %s", target, exc)
        return not target.exists()


def _scan_dir(base: Path, max_age_seconds: float, patterns: tuple[str, ...] | None) -> List[Path]:
    """Return files under ``base`` older than ``max_age_seconds`` matching ``patterns``."""
    candidates: List[Path] = []
    if not base.exists():
        return candidates
    now = time.time()
    for entry in base.iterdir():
        try:
            if not entry.is_file():
                continue
            if patterns and not any(entry.name.lower().startswith(p) for p in patterns):
                continue
            mtime = entry.stat().st_mtime
            if now - mtime > max_age_seconds:
                candidates.append(entry)
        except OSError:
            continue
    return candidates


def cleanup_old_temp_files(
    max_age_hours: float = 24.0,
    extra_dirs: Iterable[Path | str] | None = None,
) -> dict[str, int]:
    """Delete orphaned temp files older than ``max_age_hours``.

    Scans:
      - The canonical TaxFlow uploads directory.
      - The system temp directory for pdf2image/OCR scratch files.
      - Any directories supplied in ``extra_dirs``.

    Returns a summary dict mapping directory to deleted count.
    """
    max_age_seconds = max_age_hours * 3600
    summary: dict[str, int] = {}

    # Canonical upload dir.
    upload_dir = get_upload_dir()
    upload_targets = _scan_dir(upload_dir, max_age_seconds, None)
    deleted = 0
    for target in upload_targets:
        if cleanup_uploaded_file(target):
            deleted += 1
    summary[str(upload_dir)] = deleted

    # System temp dir for OCR scratch files.
    tmp_root = Path(tempfile.gettempdir())
    ocr_targets = _scan_dir(tmp_root, max_age_seconds, _OCR_PREFIXES)
    deleted = 0
    for target in ocr_targets:
        try:
            target.unlink()
            logger.info("Deleted orphaned OCR temp file: %s", target)
            deleted += 1
        except Exception as exc:  # pragma: no cover
            logger.warning("Failed to delete OCR temp file %s: %s", target, exc)
    summary[str(tmp_root)] = deleted

    # User-supplied extra dirs.
    for extra in extra_dirs or []:
        extra_path = Path(extra)
        extra_targets = _scan_dir(extra_path, max_age_seconds, None)
        deleted = 0
        for target in extra_targets:
            try:
                target.unlink()
                logger.info("Deleted orphaned temp file from extra dir: %s", target)
                deleted += 1
            except Exception as exc:  # pragma: no cover
                logger.warning("Failed to delete temp file %s: %s", target, exc)
        summary[str(extra_path)] = deleted

    return summary


def _remove_tree(path: Path) -> bool:
    """Recursively remove a directory tree, returning True on success."""
    try:
        shutil.rmtree(path, ignore_errors=True)
        return not path.exists()
    except Exception as exc:  # pragma: no cover
        logger.warning("Failed to remove temp directory %s: %s", path, exc)
        return not path.exists()


class TemporaryOCRDirectory:
    """Context manager that creates a temp dir for pdf2image output and removes it.

    Usage::

        with TemporaryOCRDirectory() as ocr_tmp:
            images = convert_from_path(pdf_path, output_folder=str(ocr_tmp))
            ...
    """

    def __init__(self, prefix: str = "taxflow_ocr_") -> None:
        self._dir = Path(tempfile.mkdtemp(prefix=prefix))

    def __enter__(self) -> Path:
        return self._dir

    def __exit__(self, exc_type, exc_val, exc_tb) -> None:  # type: ignore[no-untyped-def]
        self.close()

    def close(self) -> None:
        if self._dir.exists():
            _remove_tree(self._dir)

    @property
    def path(self) -> Path:
        return self._dir


async def _periodic_cleanup_loop(interval_hours: float, max_age_hours: float) -> None:
    """Background coroutine that runs cleanup every ``interval_hours``."""
    interval_seconds = max(60.0, interval_hours * 3600)
    while True:
        await asyncio.sleep(interval_seconds)
        try:
            summary = cleanup_old_temp_files(max_age_hours=max_age_hours)
            logger.info("Scheduled temp cleanup completed: %s", summary)
        except Exception as exc:  # pragma: no cover
            logger.exception("Scheduled temp cleanup failed: %s", exc)


def start_scheduled_cleanup(
    loop: asyncio.AbstractEventLoop | None = None,
    interval_hours: float = 24.0,
    max_age_hours: float = 24.0,
) -> asyncio.Task[None]:
    """Start the background periodic cleanup task.

    The returned Task should be attached to the application lifespan so it is
    cancelled cleanly on shutdown.
    """
    loop = loop or asyncio.get_event_loop()
    return loop.create_task(_periodic_cleanup_loop(interval_hours, max_age_hours))
