# -*- mode: python ; coding: utf-8 -*-
from PyInstaller.building.build_main import Analysis, PYZ, EXE, COLLECT
from pathlib import Path

root = Path(r"C:\Users\James Clawd\.openclaw\workspace\projects\TaxFlow-Pro\TaxFlow-Pro-v3.9")

added_files = [
    (str(root / "frontend" / "dist"), "frontend/dist"),
    (str(root / "alembic"), "alembic"),
    (str(root / "alembic.ini"), "."),
    (str(root / "version.txt"), "."),
    (str(root / "requirements.txt"), "."),
    (str(root / "categories.yaml"), "."),
    (str(root / "scripts" / "taxflow_launcher.py"), "scripts/taxflow_launcher.py"),
    (str(root / "scripts" / "backup.py"), "scripts/backup.py"),
    (str(root / "scripts" / "restore.py"), "scripts/restore.py"),
]

vendored = root / "vendored"
if vendored.exists():
    for sub in vendored.iterdir():
        if sub.is_dir():
            added_files.append((str(sub), f"vendored/{sub.name}"))

ml = root / "ml"
if ml.exists():
    added_files.append((str(ml), "ml"))

a = Analysis(
    [str(root / "scripts" / "packaging" / "launcher_adapter.py")],
    pathex=[str(root), str(root / "scripts"), str(root / "scripts" / "packaging")],
    binaries=[],
    datas=added_files,
    hiddenimports=[
        "uvicorn",
        "uvicorn.logging",
        "uvicorn.loops.auto",
        "uvicorn.protocols.http.auto",
        "uvicorn.protocols.http.h11_impl",
        "uvicorn.workers",
        "fastapi",
        "fastapi.staticfiles",
        "starlette.staticfiles",
        "starlette.responses",
        "sqlalchemy",
        "alembic",
        "backend.api",
        "backend.database",
        "backend.local.settings",
        "backend.local.secrets_loader",
        "backend.local.backup",
        "backend.local.migration_health",
        "backend.local.bootstrap",
        "backend.local.sqlcipher_engine",
        "backend.local.offline",
        "backend.local.ml_pipeline",
        "backend.local.yaml_safe",
        "backend.local.column_encryption",
        "backend.local.crypto",
        "backend.local.keyring_secret",
        "backend.local.security_random",
        "backend.local.guards",
        "backend.rls",
        "backend.audit.append_only",
        "backend.auth",
        "backend.auth_rate_limit",
        "backend.rate_limit",
        "backend.routers.auth",
        "backend.routers.accounts",
        "backend.routers.clients",
        "backend.routers.transactions",
        "backend.routers.coa",
        "backend.routers.profiles",
        "backend.routers.recurring",
        "backend.routers.upload",
        "backend.routers.export",
        "backend.routers.dashboard",
        "backend.routers.tax",
        "backend.routers.ml",
        "backend.routers.audit",
        "backend.routers.depreciation",
        "backend.routers.rules",
        "backend.routers.flags",
        "backend.routers.gl",
        "backend.routers.health",
        "backend.routers.tests",
        "backend.parsers.institution",
        "backend.parsers.sandbox",
        "backend.parsers.pdf_guard",
        "backend.services.export",
        "backend.services.flags",
        "backend.services.rules",
        "backend.services.depreciation",
        "backend.security.path_safety",
        "backend.security.request_validation",
        "backend.security.upload_validator",
        "backend.utils.temp_file_cleanup",
        "pandas",
        "pyarrow",
        "joblib",
        "sklearn",
        "sklearn.feature_extraction.text",
        "sklearn.linear_model",
        "sklearn.model_selection",
        "sklearn.metrics",
        "sklearn.pipeline",
        "pytesseract",
        "pdf2image",
        "PIL",
        "pdfplumber",
        "fpdf",
        "openpyxl",
        "cryptography",
        "keyring",
        "PyPDF2",
        "jose",
        "jose.backends",
        "bcrypt",
        "dotenv",
        "sqlcipher3.dbapi2",
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=["tkinter", "matplotlib", "pytest", "IPython", "jupyter"],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=None,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=None)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name="TaxFlowPro",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    console=True,
)

coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=False,
    upx_exclude=[],
    name="TaxFlowPro",
)
